Fix deprecated np.bool in prodigal_biolib.py
This breaks in Python 3.8+ since `np.bool` has been deprecated in favour of builtin `bool`.

```
File "/mnt/tools/tool_dependencies/_conda/envs/__gtdbtk@2.1.1/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 378, in __build_coding_base_mask
    coding_base_mask = np.zeros(self.last_coding_base[seq_id], dtype=np.bool)
  File "/mnt/tools/tool_dependencies/_conda/envs/__gtdbtk@2.1.1/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'
```